//! Generated gateway bootstrap for sdkwork-image.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub fn assemble_application_router() -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_image_app_api::gateway_mount());
    router = router.merge(sdkwork_routes_image_backend_api::gateway_mount());
    router = router.merge(sdkwork_routes_image_open_api::gateway_mount());
    ApplicationAssembly { router }
}
